### ISSUE TITLE
Create products model

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/moimoi-delivery#2]
The application should support different types of moimoi-based products. The fields should include:
* name
* description
* price

**Comment by Prince-linux** [comment]
How do we name this model??

**Comment by lcabrini** [comment]
Let's call it product. I think that is appropriate.

**Comment by Prince-linux** [comment]
Ok

**Comment by lcabrini** [comment]
I have merged the changes. Can I close?

**Comment by Prince-linux** [comment]
+1
